<?php
/**
 * @file
 * Module hook.
 */

use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_preprocess_HOOK().
 */
function bibcite_export_preprocess_bibliography(&$variables) {
  $conf = \Drupal::config('bibcite_export.settings');

  if ($conf->get('show_full')) {
    /** @var \Drupal\bibcite_entity\Entity\BibliographyInterface $entity */
    $entity = $variables['elements']['#bibliography'];

    /* @var \Drupal\bibcite_export\BibciteExportFormatManagerInterface $plugin_manager */
    $plugin_manager = \Drupal::service('plugin.manager.bibcite_export_format');

    $definitions = $plugin_manager->getDefinitions();
    $enabled = $conf->get('enabled_formats');
    $definitions = array_intersect_key($definitions, array_flip($enabled));

    $items = [];

    foreach ($definitions as $definition) {
      $url = Url::fromRoute('bibcite_export.export', [
        'bibcite_format' => $definition['id'],
        'entity_type' => $entity->getEntityTypeId(),
        'entity' => $entity->id(),
      ]);

      $items[$definition['id']] = Link::fromTextAndUrl((string) $definition['label'], $url)->toRenderable();
    }

    if ($items) {
      $variables['content']['export'] = [
        '#type' => 'fieldset',
        '#title' => t('Export'),
        'content' => [
          '#theme' => 'item_list',
          '#attributes' => [
            'class' => ['inline'],
          ],
          '#items' => $items,
        ],
      ];
    }
  }
}
