<?php
/**
 * @file
 * Module hook.
 */

use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_preprocess_HOOK().
 */
function bibcite_export_preprocess_bibliography(&$variables) {
  $conf = \Drupal::config('bibcite_export.settings');

  if ($conf->get('show_full') && isset($variables['data']['#entity'])) {
    /** @var \Drupal\bibcite_entity\Entity\BibliographyInterface $entity */
    $entity = $variables['data']['#entity'];

    /* @var \Drupal\bibcite_export\BibciteExportFormatManagerInterface $plugin_manager */
    $plugin_manager = \Drupal::service('plugin.manager.bibcite_export_format');

    $definitions = $plugin_manager->getDefinitions();
    $enabled = $conf->get('enabled_formats');
    $definitions = array_intersect_key($definitions, array_flip($enabled));

    foreach ($definitions as $definition) {
      $url = Url::fromRoute('bibcite_export.export', [
        'bibcite_format' => $definition['id'],
        'entity_type' => $entity->getEntityTypeId(),
        'entity' => $entity->id(),
      ]);

      $variables['content']['links']['#items'][] = Link::fromTextAndUrl((string) $definition['label'], $url)->toRenderable();
    }

  }
}
