<?php

/**
 * @file
 * Main module hooks.
 */

/**
 * Implements hook_theme().
 */
function bibcite_theme($existing, $type, $theme, $path) {
  return [
    'bibcite_citation' => [
      'variables' => [
        'data' => [],
        'style' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bibcite_preprocess_bibcite_citation(&$variables) {
  /** @var \Drupal\bibcite\CitationStylerInterface $styler */
  $styler = \Drupal::service('bibcite.citation_styler');
  $data = $variables['data'];

  if ($variables['style']) {
    $styler->setStyleById($variables['style']);
  }

  $variables['content'] = [
    '#markup' => $styler->render($data),
  ];
}
