<?php
/**
 * @file
 * Main module hooks.
 */

use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function bibcite_theme($existing, $type, $theme, $path) {
  return [
    'bibcite_citation' => [
      'variables' => [
        'data' => [],
        'style' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bibcite_preprocess_bibcite_citation(&$variables) {
  /** @var \Drupal\bibcite\CitationStylerInterface $styler */
  $styler = \Drupal::service('bibcite.citation_styler');
  $data = $variables['data'];

  if ($variables['style']) {
    $styler->setStyleById($variables['style']);
  }

  $variables['content'] = [
    'citation' => [
      '#markup' => $styler->render($data),
    ],
    'links' => [
      '#theme' => 'item_list',
      '#attributes' => [
        'class' => ['inline'],
      ],
      '#items' => [],
    ],
  ];

  $links_config = \Drupal::config('bibcite.settings.links');
  if ($links_config->get('links.pubmed') && !empty($data['PMID'])) {
    $url = Url::fromUri('http://www.ncbi.nlm.nih.gov/pubmed/' . $data['PMID'] . '?dopt=Abstract');

    $variables['content']['links']['#items'][] = [
      '#type' => 'link',
      '#url' => $url,
      '#title' => t('PubMed'),
    ];
  }

  if ($links_config->get('links.doi') && !empty($data['DOI'])) {
    $url = Url::fromUri('http://dx.doi.org/' . $data['DOI']);

    $variables['content']['links']['#items'][] = [
      '#type' => 'link',
      '#url' => $url,
      '#title' => t('DOI'),
    ];
  }

  if ($links_config->get('links.google_scholar') && !empty($data['title'])) {
    $url = Url::fromUri('https://scholar.google.com/scholar', [
      'query' => [
        'btnG' => 'Search+Scholar',
        'as_q' => '"' . str_replace([' ', '(', ')'], ['+'], $data['title']) . '"',
        'as_occt' => 'any',
        'as_epq' => '',
        'as_oq' => '',
        'as_eq' => '',
        'as_publication' => '',
        'as_ylo' => '',
        'as_yhi' => '',
        'as_sdtAAP' => 1,
        'as_sdtp' => 1,
      ],
    ]);

    $variables['content']['links']['#items'][] = [
      '#type' => 'link',
      '#url' => $url,
      '#title' => t('Google Scholar'),
    ];
  }
}
