<?php

/**
 * @file
 * Module hooks implementations.
 */

use Drupal\bibcite_entity\Entity\ReferenceInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_bibcite_reference_prepare_form().
 *
 * Populate form values from tempstore.
 */
function bibcite_import_bibcite_reference_prepare_form(ReferenceInterface $entity, $operation, FormStateInterface $form_state) {
  /** @var \Drupal\user\PrivateTempStore $temp_storage */
  $temp_storage = \Drupal::service('user.private_tempstore')->get('bibcite_entity_populate');
  $current_user_id = \Drupal::currentUser()->id();
  $populated_entity = $temp_storage->get($current_user_id);
  if ($populated_entity && $populated_entity instanceof ReferenceInterface) {
    foreach ($populated_entity->getFields() as $field_name => $field) {
      $entity->set($field_name, $field->getValue());
    }

    $temp_storage->delete($current_user_id);
  }
}
