<?php
/**
 * @file
 * Module hooks.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function bibcite_entity_theme($existing, $type, $theme, $path) {
  return [
    'bibliography' => array(
      'render element' => 'elements',
    ),
    'bibcite_contributor' => array(
      'render element' => 'elements',
    ),
    'bibcite_keyword' => array(
      'render element' => 'elements',
    ),
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bibcite_entity_preprocess_bibliography(array &$variables) {
  // Fetch Bibliography Entity Object.
  $bibliography = $variables['elements']['#bibliography'];

  $variables['table'] = [
    '#type' => 'table',
  ];

  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    if (Element::children($variables['elements'][$key])) {
      $title = $variables['elements'][$key]['#title'];
      unset($variables['elements'][$key]['#title']);
      $variables['table'][] = [
        'title' => [
          '#markup' => $title,
        ],
        'element' => $variables['elements'][$key],
      ];
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bibcite_entity_preprocess_bibcite_contributor(array &$variables) {
  // Fetch Contributor Entity Object.
  $bibcite_contributor = $variables['elements']['#bibcite_contributor'];

  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bibcite_entity_preprocess_bibcite_keyword(array &$variables) {
  // Fetch Keyword Entity Object.
  $bibcite_keyword = $variables['elements']['#bibcite_keyword'];

  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
