<?php

/**
 * @file
 * Module hook.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_preprocess_HOOK().
 *
 * Add export links to the citation.
 */
function bibcite_export_preprocess_bibcite_citation(&$variables) {
  $conf = \Drupal::config('bibcite_export.settings');

  if ($conf->get('show_citation') && isset($variables['data']['#entity'])) {
    /** @var \Drupal\bibcite_entity\Entity\ReferenceInterface $entity */
    $entity = $variables['data']['#entity'];
    foreach (bibcite_export_create_export_links($entity) as $link) {
      $variables['content']['links']['#items'][] = $link;
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Add export links to the table view of Reference entity.
 */
function bibcite_export_preprocess_bibcite_reference_table(&$variables) {
  $conf = \Drupal::config('bibcite_export.settings');

  if ($conf->get('show_full') && isset($variables['elements']['#bibcite_reference'])) {
    /** @var \Drupal\bibcite_entity\Entity\ReferenceInterface $entity */
    $entity = $variables['elements']['#bibcite_reference'];
    foreach (bibcite_export_create_export_links($entity) as $link) {
      $variables['content']['links']['#items'][] = $link;
    }
  }
}

/**
 * Create export links for entity.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   Entity for export.
 *
 * @return array
 *   Array of export links.
 */
function bibcite_export_create_export_links(EntityInterface $entity) {
  /** @var \Drupal\bibcite\Plugin\BibciteFormatManagerInterface $manager */
  $manager = \Drupal::service('plugin.manager.bibcite_format');
  $definitions = $manager->getExportDefinitions();

  $links = [];
  foreach ($definitions as $definition) {
    $url = Url::fromRoute('bibcite_export.export', [
      'bibcite_format' => $definition['id'],
      'entity_type' => $entity->getEntityTypeId(),
      'entity' => $entity->id(),
    ]);

    $links[] = Link::fromTextAndUrl((string) $definition['label'], $url)->toRenderable();
  }

  return $links;
}
