<?php
/**
 * @file
 * Module hooks.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function bibcite_entity_theme($existing, $type, $theme, $path) {
  return [
    'bibliography' => array(
      'render element' => 'elements',
    ),
    'bibcite_contributor' => array(
      'render element' => 'elements',
    ),
    'bibcite_keyword' => array(
      'render element' => 'elements',
    ),
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bibcite_entity_preprocess_bibliography(array &$variables) {
  /** @var \Drupal\bibcite_entity\Entity\BibliographyInterface $bibliography */
  $bibliography = $variables['elements']['#bibliography'];
  $view_mode = $variables['elements']['#view_mode'];

  // @todo Any better way to handle different view mode?
  if ($view_mode == 'citation') {
    $variables['content'] = [
      '#markup' => $bibliography->cite(),
    ];
  }
  else {
    $variables['content'] = [
      '#type' => 'table',
    ];


    foreach (Element::children($variables['elements']) as $key) {
      if (Element::children($variables['elements'][$key])) {
        $title = $variables['elements'][$key]['#title'];
        $variables['elements'][$key]['#title'] = '';
        $variables['content'][] = [
          'title' => [
            '#markup' => $title,
          ],
          'element' => $variables['elements'][$key],
        ];
      }
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bibcite_entity_preprocess_bibcite_contributor(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bibcite_entity_preprocess_bibcite_keyword(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
