<?php
/**
 * @file
 * Installation hooks.
 */

/**
 * Implements hook_install().
 *
 * Add BibTex to enabled formats.
 */
function bibcite_export_test_install() {
  /** @var \Drupal\Core\Config\ConfigFactoryInterface $config_factory */
  $config_factory = \Drupal::service('config.factory');

  $config = $config_factory->getEditable('bibcite_export.settings');
  $config->set('enabled_formats', ['bibtex']);
  $config->save();
}
